import React, { useEffect, useState, useRef } from 'react'
import {
    Accordion,
    AccordionContent,
    AccordionTitle,
    Link,
    Typography,
    UnorderedList,
    List,
} from '@modjs/core'
import { GithubIcon } from '@modjs/icons'

const CoreNavigation = () => {
    const gettingStartedAccordionRef = useRef(null)
    const apiAccordionRef = useRef(null)

    const [currentPage, setCurrentPage] = useState(null)

    const [gettingStartedAccordionOpen, setGettingStartedAccordionOpen] =
        useState(false)
    const [apiAccordionOpen, setApiAccordionOpen] = useState(false)

    //Set currentPage on mount
    useEffect(() => {
        if (typeof window !== 'undefined') {
            const page = window.location.pathname
            setCurrentPage(page)
        }
    }, [currentPage])

    //Auto open AccordionContent based on currentPage
    useEffect(() => {
        if (currentPage) {
            setGettingStartedAccordionOpen(
                /customization/.test(currentPage) ||
                    /installation/.test(currentPage),
            )
            setApiAccordionOpen(/api/.test(currentPage))
        }
    }, [apiAccordionOpen, currentPage])

    // Scroll to active link in AccordionContent
    useEffect(() => {
        if (
            (currentPage && apiAccordionRef.current) ||
            (currentPage && gettingStartedAccordionRef.current)
        ) {
            // Find the active link element
            const currentPageElement =
                apiAccordionRef.current.querySelector(
                    `[href="${currentPage}"]`,
                ) ||
                gettingStartedAccordionRef.current.querySelector(
                    `[href="${currentPage}"]`,
                )

            if (currentPageElement) {
                currentPageElement.scrollIntoView({
                    behavior: 'smooth',
                    block: 'end',
                })
            }
        }
    }, [currentPage])

    return (
        <>
            <Link
                variant="icon"
                mb={16}
                href="https://github.com/modjs-org/modjs/tree/main/packages/core"
                target="_blank"
                data-testid="CoreNavigation_link-github"
            >
                Github Repository <GithubIcon />
            </Link>
            {/* Getting Started */}

            <Accordion
                variant="transparent"
                notched={false}
                defaultOpen={gettingStartedAccordionOpen}
            >
                <AccordionTitle data-testid="CoreNavigation_accordion-getting_started">
                    <Typography variant="h3">Getting Started</Typography>
                </AccordionTitle>
                <AccordionContent ref={gettingStartedAccordionRef}>
                    <UnorderedList>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/installation"
                                active={/core\/installation$/.test(currentPage)}
                                data-testid="CoreNavigation_link-installation"
                            >
                                Installation
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/customization"
                                active={/core\/customization$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-customization"
                            >
                                Customization
                            </Link>
                        </List>
                    </UnorderedList>
                </AccordionContent>
            </Accordion>
            <Accordion
                variant="transparent"
                notched={false}
                defaultOpen={apiAccordionOpen}
            >
                <AccordionTitle data-testid="CoreNavigation_accordion-component_api">
                    <Typography variant="h3">Component API</Typography>
                </AccordionTitle>
                <AccordionContent ref={apiAccordionRef}>
                    <UnorderedList>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-accordion"
                                active={/core\/api\/react-accordion$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-accordion-api"
                            >
                                Accordion
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-accordion-content"
                                active={/core\/api\/react-accordion-content$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-accordion_content-api"
                            >
                                AccordionContent
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-accordion-title"
                                active={/core\/api\/react-accordion-title$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-accordion_title-api"
                            >
                                AccordionTitle
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-appbar"
                                active={/core\/api\/react-appbar$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-appbar-api"
                            >
                                Appbar
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-article"
                                active={/core\/api\/react-article$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-article-api"
                            >
                                Article
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-aside"
                                active={/core\/api\/react-aside$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-aside-api"
                            >
                                Aside
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-avatar"
                                active={/core\/api\/react-avatar$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-avatar-api"
                            >
                                Avatar
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-box"
                                active={/core\/api\/react-box$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-box-api"
                            >
                                Box
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-breadcrumbs"
                                active={/core\/api\/react-breadcrumbs$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-breadcrumbs-api"
                            >
                                Breadcrumbs
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-button"
                                active={/core\/api\/react-button$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-button-api"
                            >
                                Button
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-card"
                                active={/core\/api\/react-card$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-card-api"
                            >
                                Card
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-card-content"
                                active={/core\/api\/react-card-content$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-card_content-api"
                            >
                                CardContent
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-card-footer"
                                active={/core\/api\/react-card-footer$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-card_footer-api"
                            >
                                CardFooter
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-card-header"
                                active={/core\/api\/react-card-header$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-card_header-api"
                            >
                                CardHeader
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-card-media"
                                active={/core\/api\/react-card-media$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-card_media-api"
                            >
                                CardMedia
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-card-meta"
                                active={/core\/api\/react-card-meta$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-card_meta-api"
                            >
                                CardMeta
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-carousel"
                                active={/core\/api\/react-carousel$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-carousel-api"
                            >
                                Carousel
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-carousel-description"
                                active={/core\/api\/react-carousel-description$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-carousel_description-api"
                            >
                                CarouselDescription
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-carousel-excerpt"
                                active={/core\/api\/react-carousel-excerpt$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-carousel_excerpt-api"
                            >
                                CarouselExcerpt
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-carousel-footer"
                                active={/core\/api\/react-carousel-footer$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-carousel_footer-api"
                            >
                                CarouselFooter
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-carousel-item"
                                active={/core\/api\/react-carousel-item$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-carousel_item-api"
                            >
                                CarouselItem
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-carousel-media"
                                active={/core\/api\/react-carousel-media$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-carousel_media-api"
                            >
                                CarouselMedia
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-code-editor"
                                active={/core\/api\/react-code-editor$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-code_editor-api"
                            >
                                CodeEditor
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-confirm-password-field"
                                active={/core\/api\/react-confirm-password-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-confirm_password_field-api"
                            >
                                ConfirmPasswordField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-container"
                                active={/core\/api\/react-container$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-container-api"
                            >
                                Container
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-copy"
                                active={/core\/api\/react-copy$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-copy-api"
                            >
                                Copy
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-copy-response"
                                active={/core\/api\/react-copy-response$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-copy_response-api"
                            >
                                CopyResponse
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-create-password-field"
                                active={/core\/api\/react-create-password-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-create_password_field-api"
                            >
                                CreatePasswordField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-drawer"
                                active={/core\/api\/react-drawer$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-drawer-api"
                            >
                                Drawer
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-drawer-content"
                                active={/core\/api\/react-drawer-content$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-drawer_content-api"
                            >
                                DrawerContent
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-dropdown"
                                active={/core\/api\/react-dropdown$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-dropdown-api"
                            >
                                Dropdown
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-dropdown-content"
                                active={/core\/api\/react-dropdown-content$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-dropdown_content-api"
                            >
                                DropdownContent
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-email-field"
                                active={/core\/api\/react-email-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-email_field-api"
                            >
                                EmailField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-fieldset"
                                active={/core\/api\/react-fieldset$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-fieldset-api"
                            >
                                Fieldset
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-footer"
                                active={/core\/api\/react-footer$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-footer-api"
                            >
                                Footer
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-form"
                                active={/core\/api\/react-form$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-form-api"
                            >
                                Form
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-grid"
                                active={/core\/api\/react-grid$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-grid-api"
                            >
                                Grid
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-header"
                                active={/core\/api\/react-header$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-header-api"
                            >
                                Header
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-image"
                                active={/core\/api\/react-image$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-image-api"
                            >
                                Image
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-layout"
                                active={/core\/api\/react-layout$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-layout-api"
                            >
                                Layout
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-linear-progress"
                                active={/core\/api\/react-linear-progress$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-linear_progress-api"
                            >
                                LinearProgress
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-link"
                                active={/core\/api\/react-link$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-link-api"
                            >
                                Link
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-list"
                                active={/core\/api\/react-list$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-list-api"
                            >
                                List
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-main"
                                active={/core\/api\/react-main$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-main-api"
                            >
                                Main
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-message-area"
                                active={/core\/api\/react-message-area$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-message_area-api"
                            >
                                MessageArea
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-modal"
                                active={/core\/api\/react-modal$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-modal-api"
                            >
                                Modal
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-modal-content"
                                active={/core\/api\/react-modal-content$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-modal_content-api"
                            >
                                ModalContent
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-name-field"
                                active={/core\/api\/react-name-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-name_field-api"
                            >
                                NameField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-nav"
                                active={/core\/api\/react-nav$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-nav-api"
                            >
                                Nav
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-ordered-list"
                                active={/core\/api\/react-ordered-list$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-ordered_list-api"
                            >
                                OrderedList
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-password-field"
                                active={/core\/api\/react-password-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-password_field-api"
                            >
                                PasswordField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-phone-field"
                                active={/core\/api\/react-phone-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-phone_field-api"
                            >
                                PhoneField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-pill"
                                active={/core\/api\/react-pill$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-pill-api"
                            >
                                Pill
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-pre"
                                active={/core\/api\/react-pre$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-pre-api"
                            >
                                Pre
                            </Link>
                        </List>

                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-search-field"
                                active={/core\/api\/react-search-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-search_field-api"
                            >
                                SearchField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-search-results"
                                active={/core\/api\/react-search-results$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-search_results-api"
                            >
                                SearchResults
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-section"
                                active={/core\/api\/react-section$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-section-api"
                            >
                                Section
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-separator"
                                active={/core\/api\/react-separator$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-separator-api"
                            >
                                Separator
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-side-navigation"
                                active={/core\/api\/react-side-navigation$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-side_navigation-api"
                            >
                                SideNavigation
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-slideshow"
                                active={/core\/api\/react-slideshow$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-slideshow-api"
                            >
                                Slideshow
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-slideshow-description"
                                active={/core\/api\/react-slideshow-description$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-slideshow_description-api"
                            >
                                SlideshowDescription
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-slideshow-excerpt"
                                active={/core\/api\/react-slideshow-excerpt$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-slideshow_excerpt-api"
                            >
                                SlideshowExcerpt
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-slideshow-footer"
                                active={/core\/api\/react-slideshow-footer$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-slideshow_footer-api"
                            >
                                SlideshowFooter
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-slideshow-item"
                                active={/core\/api\/react-slideshow-item$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-slideshow_item-api"
                            >
                                SlideshowItem
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-slideshow-media"
                                active={/core\/api\/react-slideshow-media$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-slideshow_media-api"
                            >
                                SlideshowMedia
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-snackbar"
                                active={/core\/api\/react-snackbar$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-snackbar-api"
                            >
                                Snackbar
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-snackbar-content"
                                active={/core\/api\/react-snackbar-content$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-snackbar_content-api"
                            >
                                SnackbarContent
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-snackbar-header"
                                active={/core\/api\/react-snackbar-header$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-snackbar_header-api"
                            >
                                SnackbarHeader
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-table"
                                active={/core\/api\/react-table$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-table-api"
                            >
                                Table
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-table-body"
                                active={/core\/api\/react-table-body$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-table_body-api"
                            >
                                TableBody
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-table-data"
                                active={/core\/api\/react-table-data$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-table_data-api"
                            >
                                TableData
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-table-head"
                                active={/core\/api\/react-table-head$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-table_head-api"
                            >
                                TableHead
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-table-header"
                                active={/core\/api\/react-table-header$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-table_header-api"
                            >
                                TableHeader
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-table-row"
                                active={/core\/api\/react-table-row$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-table_row-api"
                            >
                                TableRow
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-text-field"
                                active={/core\/api\/react-text-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-text_field-api"
                            >
                                TextField
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-textarea"
                                active={/core\/api\/react-textarea$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-textarea-api"
                            >
                                TextArea
                            </Link>
                        </List>

                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-toolbar"
                                active={/core\/api\/react-toolbar$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-toolbar-api"
                            >
                                Toolbar
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-tooltip"
                                active={/core\/api\/react-tooltip$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-tooltip-api"
                            >
                                Tooltip
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-tooltip-content"
                                active={/core\/api\/react-tooltip-content$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-tooltip_content-api"
                            >
                                TooltipContent
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-typography"
                                active={/api\/react-typography$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-typography-api"
                            >
                                Typography API
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-unordered-list"
                                active={/core\/api\/react-unordered-list$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-unordered_list-api"
                            >
                                UnorderedList
                            </Link>
                        </List>
                        <List>
                            <Link
                                variant="transparent"
                                href="/core/api/react-url-field"
                                active={/core\/api\/react-url-field$/.test(
                                    currentPage,
                                )}
                                data-testid="CoreNavigation_link-url_field-api"
                            >
                                UrlField
                            </Link>
                        </List>
                    </UnorderedList>
                </AccordionContent>
            </Accordion>
        </>
    )
}

export default CoreNavigation
