version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      #TODO: use npm ci instead for automated env in order to enable caching for faster build
      - npm install @modjs/core@7.1.0
      - npm install @modjs/icons@7.1.1
      - npm install @modjs/utils@7.0.0
      - npm install @modjs/helpers@7.0.0
      - npm install next@14.2.2
      - npm install react@18.3.1
      - npm install react-dom@18.3.1
      - npm install react-redux@9.1.1
      - npm install redux@5.0.1
      - npm install redux-thunk@3.1.0
      - npm install styled-components@6.1.11
  build:
    commands:
      - npm run build:docs
  post_build:
    commands:
      - ls -la node_modules/@modjs
      - ls -la 
      #CAUTION: Ensure correct path to the out folder in the monorepo
      - ls -la docs/modjs-docs-site/v7/out/ || echo "OUT DIRECTORY DOES NOT EXIST"
      - |
        renamed_files=$(find docs/modjs-docs-site/v7/out -type f -name "*.html" -exec sh -c 'mv "$1" "${1%.html}" && echo "${1%.html}"' _ {} \;)
        for file in $renamed_files; do
          aws s3 cp "${file}" "s3://www.modjs.prashan.dev/$(basename $file)" --content-type "text/html" --metadata-directive="REPLACE"
        done
        aws s3 sync "docs/modjs-docs-site/v7/out/" "s3://www.modjs.prashan.dev/" --delete --include "*" --exclude "$(basename -a $renamed_files)"